//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2470
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2470.
// 
namespace CBSolutions.ETH.Web.TwinfieldSession {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SessionSoap", Namespace="http://www.twinfield.com/")]
    public class Session : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        public Header HeaderValue;
        
        /// <remarks/>
        public Session() {
            this.Url = "https://login.twinfield.com/webservices/session.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("HeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.twinfield.com/Logon", RequestNamespace="http://www.twinfield.com/", ResponseNamespace="http://www.twinfield.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LogonResult Logon(string user, string password, string organisation, out LogonAction nextAction, out string cluster) {
            object[] results = this.Invoke("Logon", new object[] {
                        user,
                        password,
                        organisation});
            nextAction = ((LogonAction)(results[1]));
            cluster = ((string)(results[2]));
            return ((LogonResult)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLogon(string user, string password, string organisation, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Logon", new object[] {
                        user,
                        password,
                        organisation}, callback, asyncState);
        }
        
        /// <remarks/>
        public LogonResult EndLogon(System.IAsyncResult asyncResult, out LogonAction nextAction, out string cluster) {
            object[] results = this.EndInvoke(asyncResult);
            nextAction = ((LogonAction)(results[1]));
            cluster = ((string)(results[2]));
            return ((LogonResult)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("HeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.twinfield.com/SmsLogon", RequestNamespace="http://www.twinfield.com/", ResponseNamespace="http://www.twinfield.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SMSLogonResult SmsLogon(string smsCode, out LogonAction nextAction) {
            object[] results = this.Invoke("SmsLogon", new object[] {
                        smsCode});
            nextAction = ((LogonAction)(results[1]));
            return ((SMSLogonResult)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSmsLogon(string smsCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SmsLogon", new object[] {
                        smsCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public SMSLogonResult EndSmsLogon(System.IAsyncResult asyncResult, out LogonAction nextAction) {
            object[] results = this.EndInvoke(asyncResult);
            nextAction = ((LogonAction)(results[1]));
            return ((SMSLogonResult)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("HeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.twinfield.com/SmsSendCode", RequestNamespace="http://www.twinfield.com/", ResponseNamespace="http://www.twinfield.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SmsSendCode() {
            object[] results = this.Invoke("SmsSendCode", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSmsSendCode(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SmsSendCode", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public int EndSmsSendCode(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("HeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.twinfield.com/ChangePassword", RequestNamespace="http://www.twinfield.com/", ResponseNamespace="http://www.twinfield.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ChangePasswordResult ChangePassword(string currentPassword, string newPassword, out LogonAction nextAction) {
            object[] results = this.Invoke("ChangePassword", new object[] {
                        currentPassword,
                        newPassword});
            nextAction = ((LogonAction)(results[1]));
            return ((ChangePasswordResult)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginChangePassword(string currentPassword, string newPassword, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ChangePassword", new object[] {
                        currentPassword,
                        newPassword}, callback, asyncState);
        }
        
        /// <remarks/>
        public ChangePasswordResult EndChangePassword(System.IAsyncResult asyncResult, out LogonAction nextAction) {
            object[] results = this.EndInvoke(asyncResult);
            nextAction = ((LogonAction)(results[1]));
            return ((ChangePasswordResult)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("HeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.twinfield.com/SelectCompany", RequestNamespace="http://www.twinfield.com/", ResponseNamespace="http://www.twinfield.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SelectCompanyResult SelectCompany(string company) {
            object[] results = this.Invoke("SelectCompany", new object[] {
                        company});
            return ((SelectCompanyResult)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSelectCompany(string company, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SelectCompany", new object[] {
                        company}, callback, asyncState);
        }
        
        /// <remarks/>
        public SelectCompanyResult EndSelectCompany(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SelectCompanyResult)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("HeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.twinfield.com/KeepAlive", RequestNamespace="http://www.twinfield.com/", ResponseNamespace="http://www.twinfield.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void KeepAlive() {
            this.Invoke("KeepAlive", new object[0]);
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginKeepAlive(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("KeepAlive", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public void EndKeepAlive(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("HeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.twinfield.com/Abandon", RequestNamespace="http://www.twinfield.com/", ResponseNamespace="http://www.twinfield.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Abandon() {
            this.Invoke("Abandon", new object[0]);
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAbandon(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Abandon", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public void EndAbandon(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("HeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.twinfield.com/GetRole", RequestNamespace="http://www.twinfield.com/", ResponseNamespace="http://www.twinfield.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetRole() {
            object[] results = this.Invoke("GetRole", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetRole(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetRole", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetRole(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.twinfield.com/", IsNullable=false)]
    public class Header : System.Web.Services.Protocols.SoapHeader {
        
        /// <remarks/>
        public string SessionID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public enum LogonResult {
        
        /// <remarks/>
        Ok,
        
        /// <remarks/>
        Blocked,
        
        /// <remarks/>
        Untrusted,
        
        /// <remarks/>
        Invalid,
        
        /// <remarks/>
        Deleted,
        
        /// <remarks/>
        Disabled,
        
        /// <remarks/>
        OrganisationInactive,
        
        /// <remarks/>
        ClientInvalid,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public enum LogonAction {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        SMSLogon,
        
        /// <remarks/>
        ChangePassword,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public enum SMSLogonResult {
        
        /// <remarks/>
        Ok,
        
        /// <remarks/>
        Invalid,
        
        /// <remarks/>
        TimeOut,
        
        /// <remarks/>
        Disabled,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public enum ChangePasswordResult {
        
        /// <remarks/>
        Ok,
        
        /// <remarks/>
        Invalid,
        
        /// <remarks/>
        NotDifferent,
        
        /// <remarks/>
        NotSecure,
        
        /// <remarks/>
        Disabled,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public enum SelectCompanyResult {
        
        /// <remarks/>
        Ok,
        
        /// <remarks/>
        Invalid,
    }
}
